/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.np.sc.klijent.forme.skicentar;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import rs.ac.bg.fon.np.sc.commonlib.domen.OpstiDomenskiObjekat;
import rs.ac.bg.fon.np.sc.commonlib.domen.SkiCentar;
import rs.ac.bg.fon.np.sc.klijent.forme.OpstaEkranskaForma;
import rs.ac.bg.fon.np.sc.klijent.kontrolerki.impl.KontrolerKiPromeniSkiCentarDet;

/**
 *
 * @author UrosVesic
 */
public class PromeniSkiCentarDetalji extends OpstaEkranskaForma {

    /**
     * Creates new form PromeniSkiCentarSve
     */
    private SkiCentar skiCentar;
    private final KontrolerKiPromeniSkiCentarDet kkisc;

    public PromeniSkiCentarDetalji(SkiCentar skiCentar) {
        initComponents();
        this.skiCentar = skiCentar;
        kkisc = new KontrolerKiPromeniSkiCentarDet(this);
        try {
            kkisc.soUcitajListuSkiCentara();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        pripremiFormu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSifraSkiCentra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNazivSkiCentra = new javax.swing.JTextField();
        txtNazivPlanine = new javax.swing.JTextField();
        txtRadnoVreme = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStaze = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblZicare = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnKreirajStazu = new javax.swing.JButton();
        btnObrisiStazu = new javax.swing.JButton();
        btnKreirajZicaru = new javax.swing.JButton();
        btnObrisiZicaru = new javax.swing.JButton();
        btnZapamtiSve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Sifra ski centra:");

        txtSifraSkiCentra.setEditable(false);

        jLabel2.setText("Naziv ski centra:");

        jLabel3.setText("Naziv planine:");

        jLabel4.setText("Radno vreme: ");

        tblStaze.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStaze);

        tblZicare.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblZicare);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Staze:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Zicare:");

        btnKreirajStazu.setText("Dodaj stazu");
        btnKreirajStazu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajStazuActionPerformed(evt);
            }
        });

        btnObrisiStazu.setText("Obrisi stazu");
        btnObrisiStazu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStazuActionPerformed(evt);
            }
        });

        btnKreirajZicaru.setText("Dodaj zicaru");
        btnKreirajZicaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajZicaruActionPerformed(evt);
            }
        });

        btnObrisiZicaru.setText("Obrisi zicaru");
        btnObrisiZicaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiZicaruActionPerformed(evt);
            }
        });

        btnZapamtiSve.setText("Zapamti sve");
        btnZapamtiSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapamtiSveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(227, 227, 227))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSifraSkiCentra, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNazivSkiCentra)
                            .addComponent(txtNazivPlanine)
                            .addComponent(txtRadnoVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZapamtiSve, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(273, 273, 273))))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnKreirajStazu)
                .addGap(91, 91, 91)
                .addComponent(btnObrisiStazu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKreirajZicaru)
                .addGap(93, 93, 93)
                .addComponent(btnObrisiZicaru)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifraSkiCentra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNazivSkiCentra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNazivPlanine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZapamtiSve, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRadnoVreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreirajStazu)
                    .addComponent(btnObrisiStazu)
                    .addComponent(btnKreirajZicaru)
                    .addComponent(btnObrisiZicaru))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            kkisc.SOUcitajSkiCentarDetalji();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnKreirajStazuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajStazuActionPerformed
        // TODO add your handling code here:
        kkisc.dodajStazu();
    }//GEN-LAST:event_btnKreirajStazuActionPerformed

    private void btnObrisiStazuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStazuActionPerformed
        // TODO add your handling code here:
        int row = tblStaze.getSelectedRow();
        if (row != -1) {
            kkisc.obrisiStazu(row);
            return;
        }
        JOptionPane.showMessageDialog(this, "Niste izabrali stazu za brisanje");
    }//GEN-LAST:event_btnObrisiStazuActionPerformed

    private void btnKreirajZicaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajZicaruActionPerformed
        // TODO add your handling code here:
        kkisc.dodajZicaru();
    }//GEN-LAST:event_btnKreirajZicaruActionPerformed

    private void btnObrisiZicaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiZicaruActionPerformed
        // TODO add your handling code here:
        int row = tblZicare.getSelectedRow();
        if (row != -1) {
            kkisc.obrisiZicaru(row);
            return;
        }
        JOptionPane.showMessageDialog(this, "Niste izabrali zicaru za brisanje");
    }//GEN-LAST:event_btnObrisiZicaruActionPerformed

    private void btnZapamtiSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapamtiSveActionPerformed
        try {
            // TODO add your handling code here:
            kkisc.soZapamtiSvePodatkeOSkiCentru();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnZapamtiSveActionPerformed

    @Override
    public OpstiDomenskiObjekat kreirajObjekat() {
        return new SkiCentar();
    }

    public JTable getTblStaze() {
        return tblStaze;
    }

    public JTable getTblZicare() {
        return tblZicare;
    }

    public JTextField getTxtNazivPlanine() {
        return txtNazivPlanine;
    }

    public JTextField getTxtNazivSkiCentra() {
        return txtNazivSkiCentra;
    }

    public JTextField getTxtRadnoVreme() {
        return txtRadnoVreme;
    }

    public JTextField getTxtSifraSkiCentra() {
        return txtSifraSkiCentra;
    }

    public JButton getBtnKreirajStazu() {
        return btnKreirajStazu;
    }

    public JButton getBtnKreirajZicaru() {
        return btnKreirajZicaru;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreirajStazu;
    private javax.swing.JButton btnKreirajZicaru;
    private javax.swing.JButton btnObrisiStazu;
    private javax.swing.JButton btnObrisiZicaru;
    private javax.swing.JButton btnZapamtiSve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblStaze;
    private javax.swing.JTable tblZicare;
    private javax.swing.JTextField txtNazivPlanine;
    private javax.swing.JTextField txtNazivSkiCentra;
    private javax.swing.JTextField txtRadnoVreme;
    private javax.swing.JTextField txtSifraSkiCentra;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        kkisc.pripremiFormu(skiCentar);

    }
}
